version: '2.1'

services:
  alfresco:
    image: ${DOCKER_IMAGE}
    ports:
      - 8081:8080
    #    - 8000:8000 # DEBUG
    environment:
      #    - CATALINA_OPTS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - DB_URL=jdbc:postgresql://postgresql:5432/alfresco
      - DB_DRIVER=org.postgresql.Driver
      - ALFRESCO_PROTOCOL=http
      - GLOBAL_index.subsystem.name=noindex
      - GLOBAL_ooo.enabled=false
      - GLOBAL_jodconverter.enabled=false
      - DEBUG=false
      #    - JMX_ENABLED=true
      - INDEX=noindex
      - JAVA_OPTS_PERM_GEN=-XX:PermSize=512m -XX:MaxPermSize=512m
    healthcheck:
      test: curl localhost:8080/alfresco/
      interval: 30s
      timeout: 30s
      retries: 5

  postgresql:
    image: xenit/postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco

volumes:
  postgres:
